### ISSUE TITLE
Add favicon to index

### ISSUE THREAD

**Issue by RafaelGSS** [GonzagaAccess/gonzaga-access.github.io#14]
**Is your feature request related to a problem? Please describe.**
Needs add favicon to index, the splash art has [here](https://www.figma.com/file/yP5HlDYmfsOYlwMLs0Ou4q/Acess?node-id=0%3A1)

**Comment by gregorycode** [comment]
I'll work on this.

**Comment by SafaElmali** [comment]
I want to work on this

**Comment by iamsurajdc** [comment]
@Grigory57  I already submitted PR for this one. Request for review @RafaelGSS

**Comment by RafaelGSS** [comment]
Thanks!
