### ISSUE TITLE
Add the Learn Braille to feature list

### ISSUE THREAD

**Issue by RafaelGSS** [GonzagaAccess/gonzaga-access.github.io#32]
**Describe the solution you'd like**
We have landed the _alpha_ version of [Learn Braille](https://github.com/GonzagaAccess/learn-braille-alexa) :tada:. However, this information is not available on the website. 

The information that needs to change is
![image](https://user-images.githubusercontent.com/26234614/96056838-fa5bce00-0e5d-11eb-9f54-8bf322fec53c.png)

Only change the `_Access Leitor_` to `_Aprenda Braille_` and the description is the same as skill in _additional context_

**Additional context**

- The link of skill (available only in Brazil is [here](https://www.amazon.com.br/Gonzaga-Access-Aprenda-Braille/dp/B08KTR1NM3/)) - This is important to add.

**Comment by ChandlerKlein** [comment]
Hi there, could you assign this issue to me?

**Comment by aj-ya** [comment]
Hey! Can i work on this.

**Comment by RafaelGSS** [comment]
of course. Feel free to ask anything.
